services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
    tags:
      - name: event.listener
        identifier: 'semantic-suggestion-page-analysis'

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'
