services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
    public: true

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    tags: ['backend.controller']

  # Configuration explicite pour Connection
  TYPO3\CMS\Core\Database\Connection:
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getConnectionByName']
    arguments: ['Default']

  # Configuration pour QueryBuilder
  TYPO3\CMS\Core\Database\Query\QueryBuilder:
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['pages']  # Vous pouvez ajuster cela selon vos besoins